# Generated by Django 5.1.2 on 2024-11-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person submitting the feedback', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the person', max_length=254)),
                ('subject', models.CharField(help_text='Subject of the message', max_length=150)),
                ('message', models.TextField(help_text='The message content')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the feedback was submitted')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the project', max_length=100)),
                ('image', models.ImageField(help_text='Upload an image for the portfolio item', upload_to='portfolio/')),
                ('description', models.TextField(help_text='Description of the project')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the service (e.g., Logo Design)', max_length=100)),
                ('image', models.ImageField(help_text='Upload an image for the service', upload_to='services/')),
                ('description', models.TextField(help_text='Description of the service')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='Social media platform (e.g., Facebook)', max_length=50)),
                ('url', models.URLField(help_text='URL to the social media profile')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Name of the client', max_length=100)),
                ('client_position', models.CharField(blank=True, help_text="Client's position or company name", max_length=100, null=True)),
                ('client_image', models.ImageField(blank=True, help_text='Upload an image of the client', null=True, upload_to='testimonials/')),
                ('feedback', models.TextField(help_text='Feedback or testimonial from the client')),
            ],
        ),
    ]
